services:
  app:
    image: ghcr.io/gabe-real/crashlogger:main
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - TEST_SERVER=${TEST_SERVER}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=crashlogger"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope crashlogger --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
