name: Build and Publish Docker Image

on:
  workflow_run:
    workflows: ["Build (CI)"]
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Main JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: Main JAR
          path: build/libs/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract project info
        id: project
        run: |
          # Extract from build.gradle.kts since we have the source
          PROJECT_NAME=$(grep -E '^group = ' build.gradle.kts | sed 's/group = "\(.*\)"/\1/')
          PROJECT_VERSION=$(grep -E '^version = ' build.gradle.kts | sed 's/version = "\(.*\)"/\1/')
          echo "name=${PROJECT_NAME}" >> $GITHUB_OUTPUT
          echo "version=${PROJECT_VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/crashlogger
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=${{ github.ref_name }},enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            JAVA_VERSION=21
            PROJECT_NAME=${{ steps.project.outputs.name }}
            PROJECT_VERSION=${{ steps.project.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
